name: youtube_player_interop
description: A youtube iframe player wrapper from Dart web applications
version: 0.1.2
homepage: https://www.github.com/rxlabz/youtube_player_interop
author: rxlabz <dev@rxla.bz>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  js: '^0.6.1'
  meta: '^1.1.2'

dev_dependencies:
  test: ^0.12.0
